=== BackupTheBerlios/jarmytool/core_src/src/armylists/DTD/armylist.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : armylist.dtd
    Created on : 25 March 2003, 00:14
    Author     : pasi
    Description:
        Purpose of the document follows.
-->


<!ELEMENT armylist (armyHeader|weapons|wargear|unit|model|unitUpdate|modelUpdate|modelStatGroups)* >
<!ELEMENT armyHeader (name,comment?)>
 <!ATTLIST armyHeader id ID #REQUIRED>
 <!ATTLIST armyHeader gameSystem CDATA #REQUIRED>
 
 <!ELEMENT name EMPTY>
  <!ATTLIST name value CDATA "">

 <!ELEMENT comment EMPTY>
  <!ATTLIST comment writer CDATA "">    
  <!ATTLIST comment email CDATA "">    
  <!ATTLIST comment web CDATA "">    
  <!ATTLIST comment value CDATA "">    
  
<!ELEMENT weapons (weapon)* >
 <!ELEMENT weapon EMPTY >
  <!ATTLIST weapon name CDATA #REQUIRED>
  <!ATTLIST weapon profileName CDATA #REQUIRED>
  <!ATTLIST weapon profile CDATA "">

<!ELEMENT wargear (wargearGroup)* >
 <!ELEMENT wargearGroup (wargearItem|wargearGroup)* >
  <!ELEMENT wargearItem EMPTY>
   <!ATTLIST wargearItem name CDATA "">
   <!ATTLIST wargearItem pointcost CDATA "">
   <!ATTLIST wargearItem weapon CDATA "">
   
<!ELEMENT unit (allowedModels, allowedUpdates, exclusiveModels+)>
 <!ATTLIST unit name CDATA "">
 <!ATTLIST unit minCount CDATA "">
 <!ATTLIST unit maxCount CDATA "">
 <!ATTLIST unit unitType CDATA "">
 <!ATTLIST unit minUnitSize CDATA "0">
 <!ATTLIST unit maxUnitSize CDATA "-1"> 
 
  
 <!ELEMENT allowedModels EMPTY>
  <!ATTLIST allowedModels value CDATA "">
 
 <!ELEMENT allowedUpdates EMPTY>
  <!ATTLIST allowedUpdates value CDATA "">  
  
  
 <!ELEMENT exclusiveModels EMPTY>
  <!ATTLIST exclusiveModels modelId CDATA #REQUIRED>  
  <!ATTLIST exclusiveModels otherModelIds CDATA #REQUIRED>  
  <!ATTLIST exclusiveModels inclusive CDATA "FALSE">  
   
  
  
<!ELEMENT model (allowedUpdates, allowedWargearGroups?, allowedWargear?)>
 <!ATTLIST model id ID #REQUIRED>
 <!ATTLIST model name CDATA "">  
 <!ATTLIST model pointcost CDATA "">  
 <!ATTLIST model minCount CDATA "">  
 <!ATTLIST model maxCount CDATA "">  
 <!ATTLIST model statType CDATA "">
 <!ATTLIST model statValues CDATA "">
 <!ATTLIST model counted CDATA "true">
 <!ATTLIST model defaultSelectedAmount CDATA "0">
 <!ATTLIST model isLinked CDATA "FALSE">
 
 <!ELEMENT allowedUpdates EMPTY>
  <!ATTLIST allowedUpdates value CDATA "">
 
 <!ELEMENT allowedWargear EMPTY>
  <!ATTLIST allowdWargear value CDATA ""> 

<!ELEMENT unitUpdate EMPTY>
 <!ATTLIST unitUpdate id ID #REQUIRED>  
 <!ATTLIST unitUpdate name CDATA "">
 <!ATTLIST unitUpdate pointcost CDATA "">
 <!ATTLIST unitUpdate pointcostPerModel CDATA "false">
 <!ATTLIST unitUpdate minCount CDATA "">
 <!ATTLIST unitUpdate maxCount CDATA "">
 <!ATTLIST unitUpdate defaultSelectedAmount CDATA "0">
 <!ATTLIST unitUpdate weapon CDATA "">
  
<!ELEMENT modelUpdate EMPTY>
 <!ATTLIST modelUpdate id ID #REQUIRED>  
 <!ATTLIST modelUpdate name CDATA "">
 <!ATTLIST modelUpdate pointcost CDATA "">
 <!ATTLIST modelUpdate pointcostPerModel CDATA "false">
 <!ATTLIST modelUpdate minCount CDATA "">
 <!ATTLIST modelUpdate maxCount CDATA ""> 
 <!ATTLIST modelUpdate defaultSelectedAmount CDATA "0">
 <!ATTLIST modelUpdate weapon CDATA "">

=== BackupTheBerlios/jarmytool/core_src/src/armylists/Warhammer 40.000/Exodites.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE armylist SYSTEM "../DTD/armylist.dtd">
<armylist>
<armyHeader id="header" gameSystem="Warhammer 40.000">
<name value="Exodites">
</name>
<comment value="" writer="Philip Bowles and Agis Neugebauer" email="" web="http://www.agisn.de/html/codex_exodites.html">
</comment>
</armyHeader>
<wargear>
<wargearGroup name="One-handed Weapons">
<wargearItem name="Blast Pistol" pointcost="1.0" weapon="Blast Pistol">
</wargearItem>
<wargearItem name="Close Combat Weapon " pointcost="1.0" weapon="">
</wargearItem>
<wargearItem name="Power Weapon" pointcost="12.0" weapon="">
</wargearItem>
<wargearItem name="Soulblade" pointcost="25.0" weapon="">
</wargearItem>
<wargearItem name="Witchblade (visionaries only)" pointcost="15.0" weapon="">
</wargearItem>
</wargearGroup>
<wargearGroup name="Two-handed Weapons">
<wargearItem name="Blast Carbine (cavalry only)" pointcost="1.0" weapon="">
</wargearItem>
<wargearItem name="Lasblaster" pointcost="2.0" weapon="Lasblaster">
</wargearItem>
<wargearItem name="Laser Lance (cavalry  only)" pointcost="10.0" weapon="Laser Lance">
</wargearItem>
<wargearItem name="Singing Spear (visionaries only)" pointcost="18.0" weapon="">
</wargearItem>
</wargearGroup>
<wargearGroup name="Wargear">
<wargearItem name="Haywire Grenade" pointcost="3.0" weapon="">
</wargearItem>
<wargearItem name="Plasma Grenade" pointcost="2.0" weapon="">
</wargearItem>
<wargearItem name="Powerblades" pointcost="15.0" weapon="">
</wargearItem>
<wargearItem name="Salamander" pointcost="6.0" weapon="">
</wargearItem>
<wargearItem name="Spirit Field (3+)" pointcost="20.0" weapon="">
</wargearItem>
<wargearItem name="Spirit Field (4+)" pointcost="15.0" weapon="">
</wargearItem>
<wargearItem name="Spirit Field (5+)" pointcost="10.0" weapon="">
</wargearItem>
</wargearGroup>
<wargearGroup name="Visionary Wargear">
<wargearItem name="Ghosthelm" pointcost="5.0" weapon="">
</wargearItem>
<wargearItem name="Spirit Stones" pointcost="40.0" weapon="">
</wargearItem>
<wargearItem name="Spirit Token" pointcost="5.0" weapon="">
</wargearItem>
</wargearGroup>
<wargearGroup name="Psychic Powers">
<wargearItem name="Executioner" pointcost="15.0" weapon="">
</wargearItem>
<wargearItem name="Fortune" pointcost="20.0" weapon="">
</wargearItem>
<wargearItem name="Heal" pointcost="20.0" weapon="">
</wargearItem>
<wargearItem name="Improve" pointcost="25.0" weapon="">
</wargearItem>
</wargearGroup>
<wargearGroup name="Exodite Mounts">
<wargearItem name="Dragon" pointcost="30.0" weapon="">
</wargearItem>
<wargearItem name="Dragon w/ Wraithbone helmet" pointcost="35.0" weapon="">
</wargearItem>
<wargearItem name="Pterosaurus" pointcost="25.0" weapon="">
</wargearItem>
<wargearItem name="Raptor" pointcost="30.0" weapon="">
</wargearItem>
</wargearGroup>
</wargear>
<weapons>
<weapon name="Blast Carbine" profileName="Ranged" profile="12&quot;,3,6,Assault 2">
</weapon>
<weapon name="Blast Pistol" profileName="Ranged" profile="12&quot;,3,6,Pistol">
</weapon>
<weapon name="Bright Lance" profileName="Ranged" profile="36&quot;,8,2,Assault 1">
</weapon>
<weapon name="Fusion Gun" profileName="Ranged" profile="12&quot;,6,1,Assault 1">
</weapon>
<weapon name="Lasblaster" profileName="Ranged" profile="24&quot;,3,6,Assault 2">
</weapon>
<weapon name="Laser Lance" profileName="Ranged" profile="N/A,5,5,Assault 1">
</weapon>
<weapon name="Neuro Disruptor" profileName="Ranged" profile="Template,(8),-,Assault 1">
</weapon>
<weapon name="Plasma Carbine" profileName="Ranged" profile="18&quot;,4,3,Assault 1">
</weapon>
<weapon name="Psychic Carbine / Blaster" profileName="Ranged" profile="Template,(8),-,Assault 1">
</weapon>
<weapon name="Scatter Laser" profileName="Ranged" profile="36&quot;,6,6,Heavy D6">
</weapon>
<weapon name="Shock Lance" profileName="Ranged" profile="N/A,6,5,Assault 1">
</weapon>
<weapon name="Star Lance - Burst" profileName="Ranged" profile="36&quot;,4,5,Heavy 1 Blast">
</weapon>
<weapon name="Star Lance - Single Shot" profileName="Ranged" profile="36&quot;,9,2,Heavy 1">
</weapon>
<weapon name="Starcannon" profileName="Ranged" profile="36&quot;,6,2,Heavy 3">
</weapon>
<weapon name="Thermal Lance" profileName="Ranged" profile="12&quot;,7,1,Assault 1">
</weapon>
<weapon name="Web Carbine" profileName="Ranged" profile="12&quot;,-,-,Assault 1">
</weapon>
</weapons>
<unit name="Exodite Baron Lord" minCount="0" maxCount="1" maxUnitSize="-1" minUnitSize="0" unitType="HQ">
<allowedModels value="model1">
</allowedModels>
<allowedUpdates value="">
</allowedUpdates>
</unit>
<unit name="Exodite Baron Hero" minCount="0" maxCount="-1" maxUnitSize="-1" minUnitSize="0" unitType="HQ">
<allowedModels value="model2">
</allowedModels>
<allowedUpdates value="">
</allowedUpdates>
</unit>
<unit name="Exodite Visionary" minCount="0" maxCount="-1" maxUnitSize="-1" minUnitSize="0" unitType="HQ">
<allowedModels value="model3">
</allowedModels>
<allowedUpdates value="">
</allowedUpdates>
</unit>
<unit name="Household Retinue" minCount="0" maxCount="-1" maxUnitSize="10" minUnitSize="5" unitType="HQ">
<allowedModels value="model4,model5">
</allowedModels>
<allowedUpdates value="unitUpdate1,unitUpdate2">
</allowedUpdates>
</unit>
<unit name="Exodite Dragoons" minCount="0" maxCount="1" maxUnitSize="10" minUnitSize="2" unitType="Elite">
<allowedModels value="model6,model7">
</allowedModels>
<allowedUpdates value="unitUpdate3">
</allowedUpdates>
</unit>
<unit name="Lethosaur Knights" minCount="0" maxCount="-1" maxUnitSize="10" minUnitSize="4" unitType="Elite">
<allowedModels value="model8,model9">
</allowedModels>
<allowedUpdates value="unitUpdate4,unitUpdate6,unitUpdate7">
</allowedUpdates>
</unit>
<unit name="Fusiliers" minCount="0" maxCount="-1" maxUnitSize="20" minUnitSize="5" unitType="Troop">
<allowedModels value="model10,model11,model12">
</allowedModels>
<allowedUpdates value="unitUpdate8,unitUpdate9">
</allowedUpdates>
</unit>
<unit name="Dragon Knights" minCount="0" maxCount="-1" maxUnitSize="10" minUnitSize="3" unitType="Troop">
<allowedModels value="model13,model14">
</allowedModels>
<allowedUpdates value="unitUpdate10,unitUpdate11,unitUpdate12">
</allowedUpdates>
</unit>
<unit name="Exodite Warriors" minCount="0" maxCount="-1" maxUnitSize="20" minUnitSize="5" unitType="Troop">
<allowedModels value="model15,model16,model17">
</allowedModels>
<allowedUpdates value="unitUpdate13,unitUpdate14,unitUpdate15,unitUpdate16">
</allowedUpdates>
</unit>
<unit name="Pterosaur Knights" minCount="0" maxCount="-1" maxUnitSize="10" minUnitSize="3" unitType="Fast Attack">
<allowedModels value="model18,model19">
</allowedModels>
<allowedUpdates value="unitUpdate18,unitUpdate19,unitUpdate20,unitUpdate21">
</allowedUpdates>
</unit>
<unit name="Raptor Knights" minCount="0" maxCount="-1" maxUnitSize="10" minUnitSize="4" unitType="Fast Attack">
<allowedModels value="model20,model21">
</allowedModels>
<allowedUpdates value="">
</allowedUpdates>
</unit>
<unit name="Megadon" minCount="0" maxCount="-1" maxUnitSize="-1" minUnitSize="0" unitType="Heavy Support">
<allowedModels value="model22">
</allowedModels>
<allowedUpdates value="unitUpdate22,unitUpdate23,unitUpdate24,unitUpdate25">
</allowedUpdates>
</unit>
<unit name="Scout Walker Squadron" minCount="0" maxCount="1" maxUnitSize="3" minUnitSize="1" unitType="Heavy Support">
<allowedModels value="model23,model24,model25">
</allowedModels>
<allowedUpdates value="">
</allowedUpdates>
</unit>
<unit name="Exo-suit" minCount="0" maxCount="1" maxUnitSize="-1" minUnitSize="0" unitType="Heavy Support">
<allowedModels value="model26">
</allowedModels>
<allowedUpdates value="unitUpdate26,unitUpdate27,unitUpdate28,unitUpdate29">
</allowedUpdates>
</unit>
<unitUpdate id="unitUpdate15" name="Fusion Gun" pointcostPerModel="false" pointcost="4.0" minCount="0" maxCount="4" defaultSelectedAmount="0" weapon="">
</unitUpdate>
<unitUpdate id="unitUpdate8" name="Bright Lance" pointcostPerModel="false" pointcost="10.0" minCount="0" maxCount="2" defaultSelectedAmount="0" weapon="">
</unitUpdate>
<unitUpdate id="unitUpdate23" name="Scatter Laser" pointcostPerModel="false" pointcost="25.0" minCount="0" maxCount="1" defaultSelectedAmount="0" weapon="Scatter Laser">
</unitUpdate>
<unitUpdate id="unitUpdate16" name="Psychic Blaster" pointcostPerModel="false" pointcost="3.0" minCount="0" maxCount="4" defaultSelectedAmount="0" weapon="">
</unitUpdate>
<unitUpdate id="unitUpdate7" name="Haywire Grenades" pointcostPerModel="true" pointcost="3.0" minCount="0" maxCount="1" defaultSelectedAmount="0" weapon="">
</unitUpdate>
<unitUpdate id="unitUpdate22" name="Starcannon" pointcostPerModel="false" pointcost="35.0" minCount="0" maxCount="1" defaultSelectedAmount="0" weapon="Starcannon">
</unitUpdate>
<unitUpdate id="unitUpdate9" name="Scatter Laser" pointcostPerModel="false" pointcost="10.0" minCount="0" maxCount="2" defaultSelectedAmount="0" weapon="Scatter Laser">
</unitUpdate>
<unitUpdate id="unitUpdate21" name="Web Carbine" pointcostPerModel="false" pointcost="3.0" minCount="0" maxCount="3" defaultSelectedAmount="0" weapon="Web Carbine">
</unitUpdate>
<unitUpdate id="unitUpdate6" name="Plasma Grenades" pointcostPerModel="true" pointcost="2.0" minCount="0" maxCount="1" defaultSelectedAmount="0" weapon="">
</unitUpdate>
<unitUpdate id="unitUpdate1" name="Plasma Grenades" pointcostPerModel="true" pointcost="2.0" minCount="0" maxCount="1" defaultSelectedAmount="0" weapon="">
</unitUpdate>
<unitUpdate id="unitUpdate29" name="Star Lance" pointcostPerModel="false" pointcost="40.0" minCount="0" maxCount="1" defaultSelectedAmount="0" weapon="Star Lance - Single Shot,Star Lance - Burst">
</unitUpdate>
<unitUpdate id="unitUpdate14" name="Haywire Grenades" pointcostPerModel="true" pointcost="3.0" minCount="0" maxCount="1" defaultSelectedAmount="0" weapon="">
</unitUpdate>
