=== BackupTheBerlios/jarmytool/core_src/src/gameSystems/gameSystem.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : gameSystem.dtd
    Created on : 01 July 2003, 13:27
    Author     : pasi
    Description:
        Purpose of the document follows.
-->

<!ELEMENT gameSystem ANY>
<!ELEMENT gameSystemHeader (name,points)>
 <!ATTLIST gameSystemHeader id ID #REQUIRED>

 <!ELEMENT name EMPTY>
  <!ATTLIST name complete CDATA ""> 
  <!ATTLIST name short CDATA "">
  
 <!ELEMENT points EMPTY>
  <!ATTLIST points defaultTargetPointcost CDATA "1500"> 
  
<!ELEMENT weaponProfiles (weaponProfile)*>  

 <!ELEMENT weaponProfile (weaponStatHeader)*>  
  <!ATTLIST weaponStatHeaders name CDATA #REQUIRED>
  
  <!ELEMENT weaponStatHeader EMPTY>
   <!ATTLIST weaponStatHeader name CDATA "">
  
<!ELEMENT modelStatGroups (modelStatGroup)* >
 <!ELEMENT modelStatGroup (modelStat)*>
  <!ATTLIST modelStatGroup name CDATA "">
   <!ELEMENT modelStat EMPTY>  
    <!ATTLIST modelStat symbol CDATA "">
    <!ATTLIST modelStat tooltip CDATA "">
    <!ATTLIST modelStat type CDATA "">  
    
<!ELEMENT unitTypes (unitType)* > 
   
 <!ELEMENT unitType EMPTY>
  <!ATTLIST unitType name CDATA "">
  <!ATTLIST unitType largePic CDATA "">
  <!ATTLIST unitType smallPic CDATA "">
  <!ATTLIST unitType postfix CDATA ".jpg">

=== BackupTheBerlios/jarmytool/core_src/src/gameSystems/warmaster.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE armylist SYSTEM "gameSystem.dtd">
<gameSystem>
 <gameSystemHeader id="header">
    <name complete="Warmaster" short="WM">
    </name> 
    <points defaultTargetPointcost="2000"/>
 </gameSystemHeader>
 
 <weaponProfiles>
</weaponProfiles>
 
<modelStatGroups>
<modelStatGroup name="infantry">
<modelStat symbol="S" tooltip="Size" type="INTEGER">
</modelStat>
<modelStat symbol="A" tooltip="Attacks" type="INTEGER">
</modelStat>
<modelStat symbol="H" tooltip="Hits" type="INTEGER">
</modelStat>
<modelStat symbol="Ar" tooltip="Armor" type="INTEGER">
</modelStat>
<modelStat symbol="C" tooltip="Command" type="INTEGER">
</modelStat>
</modelStatGroup>
</modelStatGroups>
 
<unitTypes>
 <unitType name="Infantry" largePic="whfb/lord" smallPic="whfb/lord_16" postfix=".jpg"/>
 <unitType name="Cavalry" largePic="whfb/hero" smallPic="whfb/hero_16" postfix=".jpg"/>
 <unitType name="Chariot" largePic="whfb/core" smallPic="whfb/core_16" postfix=".jpg"/>
 <unitType name="Artillery" largePic="whfb/spec" smallPic="whfb/spec_16" postfix=".jpg"/>
 <unitType name="Monster" largePic="whfb/rare" smallPic="whfb/rare_16" postfix=".jpg"/>
 <unitType name="Command" largePic="whfb/rare" smallPic="whfb/rare_16" postfix=".jpg"/>
</unitTypes>
 
</gameSystem>

=== BackupTheBerlios/jarmytool/core_src/src/gameSystems/FoW.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE armylist SYSTEM "gameSystem.dtd">
<!--
    Document   : FoW.xml

    Author     : pasi
    Description:
        Purpose of the document follows.
-->

<gameSystem>
 <gameSystemHeader id="header">
    <name complete="Flames of War" short="FoW">
    </name> 
    <points defaultTargetPointcost="1500"/>
 </gameSystemHeader>


<weaponProfiles>
 <weaponProfile name="Weapon">
   <weaponStatHeader name="Range"/>
   <weaponStatHeader name="ROF"/>
   <weaponStatHeader name="Anti-tank"/>
   <weaponStatHeader name="Firepower"/>
   <weaponStatHeader name="Notes"/>
 </weaponProfile> 
</weaponProfiles>
 
<modelStatGroups>


<modelStatGroup name="Infantry">
<modelStat symbol="Type" tooltip="Type" type="STRING">
</modelStat>
<modelStat symbol="Size" tooltip="Size" type="INTEGER">
</modelStat>
<modelStat symbol="Mot" tooltip="Motivation" type="STRING">
</modelStat>
<modelStat symbol="S" tooltip="Skill" type="STRING">
</modelStat>
</modelStatGroup>
  
<modelStatGroup name="Vehicle">
<modelStat symbol="M" tooltip="Mobility" type="STRING">
</modelStat>
<modelStat symbol="FA" tooltip="Front Armor" type="INTEGER">
</modelStat>
<modelStat symbol="SA" tooltip="Side Armor" type="INTEGER">
</modelStat>
<modelStat symbol="TA" tooltip="Top Armor" type="INTEGER">
</modelStat>
<modelStat symbol="Mot" tooltip="Motivation" type="STRING">
</modelStat>
<modelStat symbol="S" tooltip="Skill" type="STRING">
</modelStat>
</modelStatGroup>

<modelStatGroup name="Infantry with transport">
<modelStat symbol="Type" tooltip="Type" type="STRING">
</modelStat>
<modelStat symbol="Size" tooltip="Size" type="INTEGER">
</modelStat>
<modelStat symbol="M" tooltip="Mobility" type="STRING">
</modelStat>
<modelStat symbol="FA" tooltip="Front Armor" type="INTEGER">
</modelStat>
<modelStat symbol="SA" tooltip="Side Armor" type="INTEGER">
</modelStat>
<modelStat symbol="TA" tooltip="Top Armor" type="INTEGER">
</modelStat>
<modelStat symbol="Mot" tooltip="Motivation" type="STRING">
</modelStat>
<modelStat symbol="S" tooltip="Skill" type="STRING">
</modelStat>
</modelStatGroup>


<modelStatGroup name="Squad">
<modelStat symbol="#Bases" tooltip="Number of Bases" type="STRING">
</modelStat>
<modelStat symbol="Mot" tooltip="Motivation" type="STRING">
</modelStat>
<modelStat symbol="S" tooltip="Skill" type="STRING">
</modelStat>
</modelStatGroup>

<modelStatGroup name="Squad (2)">
<modelStat symbol="Team1" tooltip="Team 1" type="STRING"/>
<modelStat symbol="Team2" tooltip="Team 2" type="STRING"/>
<modelStat symbol="Mot" tooltip="Motivation" type="STRING">
</modelStat>
<modelStat symbol="S" tooltip="Skill" type="STRING">
</modelStat>
</modelStatGroup>

<modelStatGroup name="Squad (3)">
<modelStat symbol="Team1" tooltip="Team 1" type="STRING"/>
<modelStat symbol="Team2" tooltip="Team 2" type="STRING"/>
<modelStat symbol="Team3" tooltip="Team 3" type="STRING"/>
<modelStat symbol="Mot" tooltip="Motivation" type="STRING">
</modelStat>
<modelStat symbol="S" tooltip="Skill" type="STRING">
</modelStat>
</modelStatGroup>

<modelStatGroup name="Squad (4)">
<modelStat symbol="Team1" tooltip="Team 1" type="STRING"/>
<modelStat symbol="Team2" tooltip="Team 2" type="STRING"/>
<modelStat symbol="Team3" tooltip="Team 3" type="STRING"/>
<modelStat symbol="Team4" tooltip="Team 4" type="STRING"/>
<modelStat symbol="Mot" tooltip="Motivation" type="STRING">
</modelStat>
<modelStat symbol="S" tooltip="Skill" type="STRING">
</modelStat>
</modelStatGroup>

<modelStatGroup name="Squad (5)">
<modelStat symbol="Team1" tooltip="Team 1" type="STRING"/>
<modelStat symbol="Team2" tooltip="Team 2" type="STRING"/>
<modelStat symbol="Team3" tooltip="Team 3" type="STRING"/>
<modelStat symbol="Team4" tooltip="Team 4" type="STRING"/>
<modelStat symbol="Team5" tooltip="Team 5" type="STRING"/>
<modelStat symbol="Mot" tooltip="Motivation" type="STRING">
</modelStat>
<modelStat symbol="S" tooltip="Skill" type="STRING">
</modelStat>
</modelStatGroup>

</modelStatGroups>
 
<unitTypes>
 <unitType name="Headquaters Platoons" largePic="FoW/hq" smallPic="FoW/hq_16" postfix=".jpg"/>
 <unitType name="Combat Platoons" largePic="FoW/combat" smallPic="FoW/combat_16" postfix=".jpg"/>
 <unitType name="Weapons Platoons" largePic="FoW/weapons" smallPic="FoW/weapons_16" postfix=".jpg"/>
 <unitType name="Support Platoons" largePic="FoW/support" smallPic="FoW/support_16" postfix=".jpg"/>
 
</unitTypes>
 
</gameSystem>

=== BackupTheBerlios/jarmytool/core_src/src/gameSystems/mordheim.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE armylist SYSTEM "gameSystem.dtd">
<!--
    Document   : whfb.xml
    Author     : Nysse
    Description:
        Purpose of the document follows.
-->

<gameSystem>
 <gameSystemHeader id="header">
    <name complete="Mordheim" short="Mordheim">
    </name> 
    <points defaultTargetPointcost="500"/>
 </gameSystemHeader>
 
 <weaponProfiles>
 <weaponProfile name="Ranged">
   <weaponStatHeader name="Range"/>
   <weaponStatHeader name="Str."/>
   <weaponStatHeader name="Wounds"/>
   <weaponStatHeader name="Save"/>
   <weaponStatHeader name="Notes"/>
 </weaponProfile>  

 <weaponProfile name="Melee">
   <weaponStatHeader name="Str."/>
   <weaponStatHeader name="Wounds"/>
   <weaponStatHeader name="Save"/>
   <weaponStatHeader name="Notes"/>
 </weaponProfile>   
 
</weaponProfiles>
 
<modelStatGroups>
<modelStatGroup name="infantry">
<modelStat symbol="M" tooltip="Move" type="INTEGER">
</modelStat>
<modelStat symbol="WS" tooltip="Weapon Skill" type="INTEGER">
</modelStat>
<modelStat symbol="BS" tooltip="Ballistic Skill" type="INTEGER">
</modelStat>
<modelStat symbol="S" tooltip="Strength" type="INTEGER">
</modelStat>
<modelStat symbol="T" tooltip="Toughness" type="INTEGER">
</modelStat>
<modelStat symbol="W" tooltip="Wounds" type="INTEGER">
</modelStat>
<modelStat symbol="I" tooltip="Initiative" type="INTEGER">
</modelStat>
<modelStat symbol="A" tooltip="Attacks" type="INTEGER">
</modelStat>
<modelStat symbol="Ld" tooltip="Leadership" type="INTEGER">
</modelStat>
<modelStat symbol="XP" tooltip="Experience" type="INTEGER">
</modelStat>
</modelStatGroup>
</modelStatGroups>
 
<unitTypes>
 <unitType name="Heroes" largePic="whfb/lord" smallPic="whfb/lord_16" postfix=".jpg"/>
 <unitType name="Henchmen" largePic="whfb/core" smallPic="whfb/core_16" postfix=".jpg"/>
 <unitType name="Hired Swords" largePic="whfb/hero" smallPic="whfb/hero_16" postfix=".jpg"/>
 <unitType name="Dramatica Personae" largePic="whfb/spec" smallPic="whfb/spec_16" postfix=".jpg"/>
</unitTypes>
 
</gameSystem>

=== BackupTheBerlios/jarmytool/core_src/src/gameSystems/Dirtside 2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE armylist SYSTEM "gameSystem.dtd">
<!--
    Document   : Dirtside 2.xml
    Created on : july sometime 2004
    Author     : Oscar Almer
    Description:
        Purpose of the document follows.
-->

<gameSystem>
 <gameSystemHeader id="header">
    <name complete="Dirtside 2" short="DS2">
    </name> 
    <points defaultTargetPointcost="1500"/>
 </gameSystemHeader>


<weaponProfiles>
 <weaponProfile name="Ranged">
   <weaponStatHeader name="Close Range"/>
   <weaponStatHeader name="Die"/>
   <weaponStatHeader name="Valid Damage Chits"/>
   <weaponStatHeader name="Medium Range"/>
   <weaponStatHeader name="Die"/>
   <weaponStatHeader name="Valid Damage Chits"/>
   <weaponStatHeader name="Long Range"/>
   <weaponStatHeader name="Die"/>
   <weaponStatHeader name="Valid Damage Chits"/>
   <weaponStatHeader name="Notes"/>
 </weaponProfile> 

</weaponProfiles>

<modelStatGroups>

<modelStatGroup name="vehicle">
<modelStat symbol="Size" tooltip="The size of the vehicle (1-5)" type="INTEGER">
</modelStat>
<modelStat symbol="Basic Sig." tooltip="The basic die to roll for defense" type="STRING">
</modelStat>

<modelStat symbol="Stealth" tooltip="modifier to the basic roll for defense" type="INTEGER">
</modelStat>
<modelStat symbol="ETD" tooltip="Effective Target Die" type="STRING">
</modelStat>

<modelStat symbol="Mobility" tooltip="" type="STRING">
</modelStat>
<modelStat symbol="Movement" tooltip="" type="INTEGER">
</modelStat>

<modelStat symbol="FC" tooltip="Fire Control Value" type="STRING">
</modelStat>
<!--<modelStat symbol="ECM" tooltip="Electronic Counter Measures" type="STRING">
</modelStat>
ECM is a fixed value stat, so can be applied as an upgrade
-->

<modelStat symbol="FA" tooltip="Front Armour" type="INTEGER">
</modelStat>
<modelStat symbol="SA" tooltip="Side Armour" type="INTEGER">
</modelStat>

</modelStatGroup>


<modelStatGroup name="infantry">
<modelStat symbol="Type" tooltip="The type of the infantry" type="STRING">
</modelStat>
<modelStat symbol="Range" tooltip="The maximum range of the Element" type="STRING">
</modelStat>

<modelStat symbol="Damage" tooltip="Maximum amount of damage element can take in one go" type="INTEGER">
</modelStat>


<modelStat symbol="Mobility" tooltip="" type="STRING">
</modelStat>
<modelStat symbol="Movement" tooltip="" type="INTEGER">
</modelStat>

<!--<modelStat symbol="ECM" tooltip="Electronic Counter Measures" type="STRING">
</modelStat>
ECM is a fixed value stat, so can be applied as an upgrade
-->
</modelStatGroup>

</modelStatGroups>

<unitTypes>
<unitType name="Elements" largePic="DS2/group_32" smallPic="DS2/group_16" postfix=".jpg"/>
<unitType name="Platoons" largePic="DS2/platoon_32" smallPic="DS2/platoon_16" postfix=".jpg"/>
 
</unitTypes>
 
</gameSystem>

=== BackupTheBerlios/jarmytool/core_src/src/gameSystems/LOTR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE armylist SYSTEM "gameSystem.dtd">
<!--
    Document   : LOTR.xml
    Author     : Matt
    Description:
        A new system of LOTR for jARMY tool.
-->

<gameSystem>
 <gameSystemHeader id="header">
    <name complete="Lord of The Rings" short="LOTR">
    </name> 
    <points defaultTargetPointcost="1000"/>
 </gameSystemHeader>
 
 <weaponProfiles>
 <weaponProfile name="Melee">
   <weaponStatHeader name="Str."/>
   <weaponStatHeader name="Wounds"/>
   <weaponStatHeader name="Save"/>
   <weaponStatHeader name="Notes"/>
 </weaponProfile>   
 
</weaponProfiles>
 
<modelStatGroups>

<modelStatGroup name="warriors">
<modelStat symbol="F" tooltip="Fight Skill" type="INTEGER">
</modelStat>
<modelStat symbol="S" tooltip="Strength" type="INTEGER">
</modelStat>
<modelStat symbol="D" tooltip="Defence" type="INTEGER">
</modelStat>
<modelStat symbol="A" tooltip="Attacks" type="INTEGER">
</modelStat>
<modelStat symbol="W" tooltip="Wounds" type="INTEGER">
</modelStat>
<modelStat symbol="C" tooltip="Courage" type="INTEGER">
</modelStat>
</modelStatGroup>

<modelStatGroup name="heroes">
<modelStat symbol="F" tooltip="Fight Skill" type="INTEGER">
</modelStat>
<modelStat symbol="S" tooltip="Strength" type="INTEGER">
</modelStat>
<modelStat symbol="D" tooltip="Defence" type="INTEGER">
</modelStat>
<modelStat symbol="A" tooltip="Attacks" type="INTEGER">
</modelStat>
<modelStat symbol="W" tooltip="Wounds" type="INTEGER">
</modelStat>
<modelStat symbol="C" tooltip="Courage" type="INTEGER">
</modelStat>
<modelStat symbol="M" tooltip="Might" type="INTEGER">
</modelStat>
<modelStat symbol="Wi" tooltip="Will" type="INTEGER">
</modelStat>
<modelStat symbol="Fa" tooltip="Fate" type="INTEGER">
</modelStat>
</modelStatGroup>

</modelStatGroups>
 
<unitTypes>
  <unitType name="Heroes" largePic="whfb/hero" smallPic="whfb/hero_16" postfix=".jpg"/>
 <unitType name="Warriors" largePic="whfb/core" smallPic="whfb/core_16" postfix=".jpg"/>
</unitTypes>
 
</gameSystem>

=== BackupTheBerlios/jarmytool/core_src/src/gameSystems/whfb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE armylist SYSTEM "gameSystem.dtd">
<!--
    Document   : whfb.xml
    Author     : pasi
    Description:
        Purpose of the document follows.
-->

<gameSystem>
 <gameSystemHeader id="header">
    <name complete="Warhammer Fantasy Battle" short="WHFB">
    </name> 
    <points defaultTargetPointcost="2000"/>
 </gameSystemHeader>
 
 <weaponProfiles>
 <weaponProfile name="Ranged">
   <weaponStatHeader name="Range"/>
   <weaponStatHeader name="Str."/>
   <weaponStatHeader name="Wounds"/>
   <weaponStatHeader name="Save"/>
   <weaponStatHeader name="Notes"/>
 </weaponProfile>  

 <weaponProfile name="Melee">
   <weaponStatHeader name="Str."/>
   <weaponStatHeader name="Wounds"/>
   <weaponStatHeader name="Save"/>
   <weaponStatHeader name="Notes"/>
 </weaponProfile>   
 
</weaponProfiles>
 
<modelStatGroups>
<modelStatGroup name="infantry">
<modelStat symbol="M" tooltip="Move" type="INTEGER">
</modelStat>
<modelStat symbol="WS" tooltip="Weapon Skill" type="INTEGER">
</modelStat>
<modelStat symbol="BS" tooltip="Ballistic Skill" type="INTEGER">
</modelStat>
<modelStat symbol="S" tooltip="Strength" type="INTEGER">
</modelStat>
<modelStat symbol="T" tooltip="Toughness" type="INTEGER">
</modelStat>
<modelStat symbol="W" tooltip="Wounds" type="INTEGER">
</modelStat>
<modelStat symbol="I" tooltip="Initiative" type="INTEGER">
</modelStat>
<modelStat symbol="A" tooltip="Attacks" type="INTEGER">
</modelStat>
<modelStat symbol="Ld" tooltip="Leadership" type="INTEGER">
</modelStat>
</modelStatGroup>
</modelStatGroups>
 
<unitTypes>
 <unitType name="Lords" largePic="whfb/lord" smallPic="whfb/lord_16" postfix=".jpg"/>
 <unitType name="Heroes" largePic="whfb/hero" smallPic="whfb/hero_16" postfix=".jpg"/>
 <unitType name="Core Units" largePic="whfb/core" smallPic="whfb/core_16" postfix=".jpg"/>
 <unitType name="Special Units" largePic="whfb/spec" smallPic="whfb/spec_16" postfix=".jpg"/>
 <unitType name="Rare Units" largePic="whfb/rare" smallPic="whfb/rare_16" postfix=".jpg"/>
</unitTypes>
 
</gameSystem>

=== BackupTheBerlios/jarmytool/core_src/src/gameSystems/wh40k.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE armylist SYSTEM "gameSystem.dtd">
<!--
    Document   : wh40k.xml
    Created on : 01 July 2003, 13:26
    Author     : pasi
    Description:
        Purpose of the document follows.
-->

<gameSystem>
 <gameSystemHeader id="header">
    <name complete="Warhammer 40.000" short="WH40k">
    </name> 
    <points defaultTargetPointcost="1500"/>
 </gameSystemHeader>


<weaponProfiles>
 <weaponProfile name="Ranged">
   <weaponStatHeader name="Range"/>
   <weaponStatHeader name="Str."/>
   <weaponStatHeader name="AP"/>
   <weaponStatHeader name="Type"/>
   <weaponStatHeader name="Notes"/>
 </weaponProfile> 
 <weaponProfile name="Ordnance">
   <weaponStatHeader name="Range"/>
   <weaponStatHeader name="Str."/>
   <weaponStatHeader name="AP"/>
   <weaponStatHeader name="Type"/>
   <weaponStatHeader name="Notes"/>
 </weaponProfile>  
 <weaponProfile name="Melee">
    <weaponStatHeader name="Range"/>
   <weaponStatHeader name="Modifiers"/>
   <weaponStatHeader name="Notes"/>
 </weaponProfile>   
 
</weaponProfiles>
 
<modelStatGroups>
<modelStatGroup name="Orbital strike">
<modelStat symbol="Str" tooltip="Strength" type="INTEGER">
</modelStat>
<modelStat symbol="AP" tooltip="AP value" type="INTEGER">
</modelStat>
</modelStatGroup> 
  
<modelStatGroup name="vehicle">
<modelStat symbol="Front Armour" tooltip="Front Armor" type="INTEGER">
</modelStat>
<modelStat symbol="Side Armour" tooltip="Side Armor" type="INTEGER">
</modelStat>
<modelStat symbol="Rear Armour" tooltip="Rear Armor" type="INTEGER">
</modelStat>
<modelStat symbol="BS" tooltip="Ballistic Skill" type="INTEGER">
</modelStat>
</modelStatGroup>
<modelStatGroup name="walker">
<modelStat symbol="WS" tooltip="Weapon Skill" type="INTEGER">
</modelStat>
<modelStat symbol="BS" tooltip="Ballistic Skill" type="INTEGER">
</modelStat>
<modelStat symbol="S" tooltip="Strength" type="INTEGER">
</modelStat>
<modelStat symbol="Front Armour" tooltip="Front Armor" type="INTEGER">
</modelStat>
<modelStat symbol="Side Armour" tooltip="Side Armor" type="INTEGER">
</modelStat>
<modelStat symbol="Rear Armour" tooltip="Rear Armor" type="INTEGER">
</modelStat>
<modelStat symbol="I" tooltip="Initiative" type="INTEGER">
</modelStat>
<modelStat symbol="A" tooltip="Attacks" type="INTEGER">
</modelStat>

</modelStatGroup>
<modelStatGroup name="infantry">
<modelStat symbol="WS" tooltip="Weapon Skill" type="INTEGER">
</modelStat>
<modelStat symbol="BS" tooltip="Ballistic Skill" type="INTEGER">
</modelStat>
<modelStat symbol="S" tooltip="Strength" type="INTEGER">
</modelStat>
<modelStat symbol="T" tooltip="Toughness" type="INTEGER">
</modelStat>
<modelStat symbol="W" tooltip="Wounds" type="INTEGER">
</modelStat>
<modelStat symbol="I" tooltip="Initiative" type="INTEGER">
</modelStat>
<modelStat symbol="A" tooltip="Attacks" type="INTEGER">
</modelStat>
<modelStat symbol="LD" tooltip="Leadership" type="INTEGER">
</modelStat>
<modelStat symbol="Save" tooltip="Save" type="STRING">
</modelStat>
</modelStatGroup>
</modelStatGroups>
 
<unitTypes>
 <unitType name="HQ" largePic="wh40k/hq_30" smallPic="wh40k/hq_16" postfix=".jpg"/>
 <unitType name="Elite" largePic="wh40k/elite_30" smallPic="wh40k/elite_16" postfix=".jpg"/>
 <unitType name="Troop" largePic="wh40k/troop_30" smallPic="wh40k/troop_16" postfix=".jpg"/>
 <unitType name="Fast Attack" largePic="wh40k/fastAttack_30" smallPic="wh40k/fastAttack_16" postfix=".jpg"/>
 <unitType name="Heavy Support" largePic="wh40k/heavySupport_30" smallPic="wh40k/heavySupport_16" postfix=".jpg"/>
</unitTypes>
 
</gameSystem>
